### ISSUE TITLE
Fork?

### ISSUE THREAD

**Issue by dblock** [kslazarev/numbers_and_words#125]
Unfortunately @kslazarev is missing ;( Is it time to fork this gem and publish it under a new name? There're a few people with access to this repo, but not admin access to add new collaborators. I am happy to do the work, add your +1s.

**Comment by benlangfeld** [comment]
:+1:

**Comment by bklang** [comment]
:+1:

**Comment by sorich87** [comment]
:+1:

**Comment by miks** [comment]
I think bigest problem is to get new library name not forking.
Any suggestions?
https://rubygems.org/gems/numbers_to_words is already taken.

**Comment by amuino** [comment]
Something like "two"? (Or any other number in words)

**Comment by dblock** [comment]
I managed to get a hold of @kslazarev and got gem owner access. Will make a release tomorrow and will try to get this setup with more owners and maintainers from the frequent contributors!

**Comment by miks** [comment]
Finally.

**Comment by amuino** [comment]
This issue can be closed then?

**Comment by dblock** [comment]
I've published 0.10.5. We now have me and @miks both with r/w access and gem ownership on Rubygems. If anyone also has r/w access to this repo that we don't know about, please speak up and I'll add you to Rubygems as well.

**Comment by eLod** [comment]
i think i have r/w access to github repo, but i really only worked on hu stuff, i don't think i need r/w access to rubygems.

**Comment by dblock** [comment]
@eLod I am just trying to make sure if a piano falls on my head we have reasonable people who can continue supporting this or other new people that care or at least have some context. What do you think?

**Comment by sorich87** [comment]
@dblock I have r/w access too.
