### ISSUE TITLE
Wrong dependencies management makes the gem require activesupport 5.0 thus Ruby 2.2.2

### ISSUE THREAD

**Issue by Koroeskohr** [kslazarev/numbers_and_words#130]
https://github.com/kslazarev/numbers_and_words/blob/master/numbers_and_words.gemspec#L172

With the recent release of Rails 5, the gem now requires ActiveSupport 5.0 because the major wasn't fixed, thus Ruby 2.2.2. A gem I work with requires numbers_and_words and runs Ruby 2.1.0 and I can't load my environment through `bundle install`.

**Comment by jlduran** [comment]
> the gem now requires ActiveSupport 5.0

I don't think so: https://github.com/kslazarev/numbers_and_words/blob/master/Gemfile#L4. It should use any version of `activesupport`.

Do you mind posting a sample `Gemfile` that reproduces the issue?

**Comment by Koroeskohr** [comment]
My gem just has those two dependencies in the .gemspec file : 
```
spec.add_runtime_dependency "numbers_and_words"
spec.add_runtime_dependency "reform"
```
and is supposed to serve apps that use Ruby 2.1. When running the test suite for the gem out of a Rails app, it fetches ActiveSupport 5.0.0, which asks for Ruby 2.2.2. Probably an inevitable caveat, requiring a forced ActiveSupport version on my end, even though my application doesn't depend on it

**Comment by dblock** [comment]
If you want a lower version of AS than 5, you should tell your app in Gemfile with `gem 'activesupport', '~> 4.0'` for example, otherwise it always tries to select the most recent one.

I'll close this, it works as designed I believe.

**Comment by jlduran** [comment]
> Probably an inevitable caveat, requiring a forced ActiveSupport version on my end

Exactly, you should add that restriction on your ` Gemfile`

**Comment by dblock** [comment]
@jlduran Are you saying we should add it in `numbers_and_words`? I don't agree. This gem works well with ActiveSupport 5.0, your problem is that it brings a version of Ruby you don't want, no?

**Comment by eLod** [comment]
@dblock i believe he meant @Koroeskohr 's gemfile, the same you suggested. I think we all agree, that @Koroeskohr 's problem is that he wants to use numbers_and_words, but by default that fetches AS 5.0 for him, which requires ruby 2.2, while he wants 2.1. the solution as both of you said is just pin AS in his gemfile.

**Comment by jlduran** [comment]
> @dblock wrote:
> Are you saying we should add it in numbers_and_words?

No, it was a suggestion for @Koroeskohr's `.gemspec` file.

He can, either create a `Gemfile` and restrict AS < 5, even a `.ruby-version` file to build the gem (this would be a way of doing it without including the dependency in his `.gemspec` file) or – the proper way – forcing the dependency on his `.gemspec` file, after all, is his gem that is not compatible with AS 5, even if it does not uses AS directly, it is needed by `numbers_and_words` (imagine I try to include his gem on a Rails 5 project, for instance).

**Comment by eLod** [comment]
@jlduran @dblock well reading his description again he said 'a gem i work with requires numbers_and_words'. i'm not sure if that means developing an app/project that depends on a gem (that depends on numbers_and_words) or developing a gem (that depends on numbers_and_words). i just tested, and bundle install with a Gemfile that only has numbers_and_words in it on ruby 2.1 does give you an error (`Gem::InstallError: activesupport requires Ruby version >= 2.2.2.`). so if he is developing an app/project that runs on 2.1 he should just pin AS < 5 himself in his own Gemfile, if he is developing a gem the users of his gem should pin AS < 5 in their own Gemfile.
