### ISSUE TITLE
Crashing Spanish Translations

### ISSUE THREAD

**Issue by kuronae12** [kslazarev/numbers_and_words#138]
I try to translate some figures into Spanish, but I run into a

uninitialized constant NumbersAndWords::Strategies::FiguresConverter::Decorators::Es error

Similar to #107 but in Spanish, only happens to Float numbers.

**Comment by jlduran** [comment]
There is no support for floats in Spanish yet.

But the error thrown should be more descriptive.

**Comment by dblock** [comment]
Maybe someone can contribute both?
