### ISSUE TITLE
Why included .yml languages as internal instead of document them and let user customize?

### ISSUE THREAD

**Issue by tommyalvarez** [kslazarev/numbers_and_words#160]
For each new language added or customization for specific language (like Spanish - Argentinian or portuguese Brasilian), we need to add a pull request adding a new .yml file and tests. Why not simply document what .yml config is expected and let user fill it up, like gems like devise does for customizing sign in / sign up translations ?

**Comment by jlduran** [comment]
Every language behaves different internally, as well as every regional variation.

To use the Portuguese you mentioned, as an example, the Brazilian version uses the [short scale](https://en.wikipedia.org/wiki/Long_and_short_scales#Short_scale), in Portugal, the [long scale](https://en.wikipedia.org/wiki/Long_and_short_scales#Long_scale) is used.

For Spanish, luckily the numbers are the same.

**Comment by tommyalvarez** [comment]
@jlduran i understand., thanks!
