### ISSUE TITLE
Wrong precision 2 for spanish

### ISSUE THREAD

**Issue by agborrego92** [kslazarev/numbers_and_words#164]
This gem is failing for this case

`I18n.with_locale(:es) { 5.1.to_words(precision: 2)}`

Output: `cinco con diez centésima`

Expected output: `cinco con diez centésimas`

I think the problem could be in `/lib/numbers_and_words/strategies/figures_converter/decorators/es/fractional.rb`. Comparing the method `figures` with other translations, it doesn't reverse the `@strategy.figures` as english for example.

Reversing the figures leads to return the correct result for Spanish

**Comment by jlduran** [comment]
@agborrego92 Thank you for reporting this bug. It should be fixed by #165.

Expect a new gem by the weekend.
