### ISSUE TITLE
Incorrect joiner for some Dutch examples

### ISSUE THREAD

**Issue by mvz** [kslazarev/numbers_and_words#181]
The following examples are not correct:
32 -> 'tweeendertig', should be 'tweeëndertig'
43 -> 'drieenveertig', should be 'drieënveertig'

The 'e' becomes a 'ë' in these cases.

I'm working on a pull request but need to gain a bit more understanding of the code to figure out how best to implement this.

**Comment by jlduran** [comment]
Thank you for reporting a bug!

We might be able to offer assistance. If those are the only two cases where the joiner changes, it should be easy to fix.

If you could push a WIP with some failing tests, it would be of great!

**Comment by mvz** [comment]
@jlduran done! See #182. I'm wondering whether the knowledge that this happens with the 2 and the 3 should live in the ruby file or the yaml file ...

**Comment by jlduran** [comment]
Closed by #182
