### ISSUE TITLE
When the numbers start with 0 it showing incorrect string value.

### ISSUE THREAD

**Issue by gokulsujan** [kslazarev/numbers_and_words#196]
![Screenshot from 2024-02-14 13-51-24](https://github.com/kslazarev/numbers_and_words/assets/62180450/11d87dda-5ca9-4bfb-b243-ee9802d4d7f6)

**Comment by dblock** [comment]
Ruby considers all integers with leading zeros as octal. I like the detailed explanation in https://stackoverflow.com/questions/28545559/how-to-work-with-leading-zeros-in-integers.

```ruby
> 00220
 => 144 

> 0d0220
 => 220 
```
