### ISSUE TITLE
create development guidelines

### ISSUE THREAD

**Issue by eLod** [kslazarev/numbers_and_words#74]
when we have a new contributor it is somewhat difficult for him to know all the style this project uses (like topic branches, etc.), so we should have a markdown file in the repo, or a wiki page where we can collect the guidelines so new contributors can learn them. @kslazarev what do you think?

**Comment by dblock** [comment]
I've committed a contributing document, we can iterate over it, https://github.com/kslazarev/numbers_and_words/blob/master/CONTRIBUTING.md - please ... contribute. 

@eLod @jlduran Do you two have r/w access to this repo? I can add you to Rubygems as well so we can make sure this project doesn't disappear :) Still trying to get owner/admin access to the repo from @kslazarev too so we can add other contributors.

**Comment by eLod** [comment]
@dblock i think @kslazarev already added r/w access to the repo for me, not rubygems though.  i dont think i have rubygems access.

**Comment by dblock** [comment]
@eLod What's your Rubygems email? Feel free to email me at dblock[at]dblock[dot]org.

**Comment by eLod** [comment]
@dblock fine with me, email sent.
