### ISSUE TITLE
Release 0.11.0

### ISSUE THREAD

**Issue by kslazarev** [kslazarev/numbers_and_words#78]

**Comment by miks** [comment]
@kslazarev can you give me permissions on rubygems for numbers_and_words?
I can make some releases finally.

**Comment by dblock** [comment]
At the very least the CHANGLEOG is not up-to-date, a number of PRs were not in it. Someone could help @kslazarev with that? Looks like he's the only person with rubygems ownerships ...

**Comment by dblock** [comment]
Please add your +1 to forking this, https://github.com/kslazarev/numbers_and_words/issues/125.

**Comment by dblock** [comment]
I've published 0.10.5. We now have me and @miks both with r/w access and gem ownership on Rubygems. If anyone also has r/w access to this repo that we don't know about, please speak up and I'll add you to Rubygems as well.
